name: music_player_3
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  get: ^4.6.6
  platform: ^3.1.5
  just_audio: ^0.9.38
  audio_service: ^0.18.0
  rxdart: ^0.27.7
  flutter_local_notifications: ^17.2.1+1
  provider: ^6.0.0
  shared_preferences: ^2.0.8
  flutter_notification_listener: ^1.3.4
  http: ^1.2.1
  dio: ^5.4.3+1
  path_provider: ^2.0.11
  audioplayers: ^6.0.0
  url_launcher: ^6.0.9
  flutter_web_auth_2: ^3.1.2
  google_nav_bar: ^5.0.6
  just_audio_background: ^0.0.1-beta.12
  fluentui_system_icons: ^1.1.243
  connectivity_plus: ^6.0.3
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  flutter_displaymode: ^0.6.0
  on_audio_query: ^2.9.0
  marquee: ^2.2.3
  text_scroll: ^0.2.0
  scroll_loop_auto_scroll: ^0.0.5
  scrolling_text: ^0.0.4
  file_picker: ^8.1.3
  audiotagger: ^2.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/music_note.png
