// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIHisYQv1ozZW1w4e1JtxdbSdzDO6bX_Q',
    appId: '1:865750359701:android:9d274d2d1d804e58afc59c',
    messagingSenderId: '865750359701',
    projectId: 'assistant-adce2',
    databaseURL: 'https://assistant-adce2-default-rtdb.firebaseio.com',
    storageBucket: 'assistant-adce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtmES2AfxL6QXPwwkV4hYp-keVeD6qLJs',
    appId: '1:865750359701:ios:8f4b83e6167055fcafc59c',
    messagingSenderId: '865750359701',
    projectId: 'assistant-adce2',
    databaseURL: 'https://assistant-adce2-default-rtdb.firebaseio.com',
    storageBucket: 'assistant-adce2.appspot.com',
    iosBundleId: 'com.example.musicPlayer3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXj0IzWK73wODUXNlVQgwS_b9RFBGtpQ0',
    appId: '1:865750359701:web:ae5942f280e83316afc59c',
    messagingSenderId: '865750359701',
    projectId: 'assistant-adce2',
    authDomain: 'assistant-adce2.firebaseapp.com',
    databaseURL: 'https://assistant-adce2-default-rtdb.firebaseio.com',
    storageBucket: 'assistant-adce2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtmES2AfxL6QXPwwkV4hYp-keVeD6qLJs',
    appId: '1:865750359701:ios:8f4b83e6167055fcafc59c',
    messagingSenderId: '865750359701',
    projectId: 'assistant-adce2',
    databaseURL: 'https://assistant-adce2-default-rtdb.firebaseio.com',
    storageBucket: 'assistant-adce2.appspot.com',
    iosBundleId: 'com.example.musicPlayer3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXj0IzWK73wODUXNlVQgwS_b9RFBGtpQ0',
    appId: '1:865750359701:web:a5bf538ccaf99171afc59c',
    messagingSenderId: '865750359701',
    projectId: 'assistant-adce2',
    authDomain: 'assistant-adce2.firebaseapp.com',
    databaseURL: 'https://assistant-adce2-default-rtdb.firebaseio.com',
    storageBucket: 'assistant-adce2.appspot.com',
  );

}